Repository LUNCH-CHAT/BACKEND, pull requests merged in 2025-08, with the labels that each got.

#71 [FEAT] 이달의 멘토 신청 기능 구현
  .gitignore
  build.gradle
  src/main/java/com/lunchchat/domain/match/controller/MentorController.java
  src/main/java/com/lunchchat/domain/match/dto/MentorDTO.java
  src/main/java/com/lunchchat/domain/match/service/MentorService.java
  src/main/java/com/lunchchat/global/config/security/GoogleSheetsConfig.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: ✨ FEAT

#75 [DEPLOY] 무중단 배포 도입 (Rolling Deployment)
  .github/workflows/deploy.yml
Labels: 🌏 Deploy

#79 [REFACTOR] 채팅 관련 페이징 처리
  src/main/java/com/lunchchat/LaunchatApplication.java
  src/main/java/com/lunchchat/domain/chat/controller/ChatRoomController.java
  src/main/java/com/lunchchat/domain/chat/entity/ChatRoom.java
  src/main/java/com/lunchchat/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/lunchchat/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/lunchchat/domain/chat/service/ChatMessageService.java
  src/main/java/com/lunchchat/domain/chat/service/ChatRoomService.java
  src/main/java/com/lunchchat/global/apiPayLoad/CursorPaginatedResponse.java
  src/main/java/com/lunchchat/global/apiPayLoad/code/status/ErrorStatus.java
Labels: 🔨 Refactor

#77 [CHORE] 최신순 정렬 updatedAt필터링 수정
  src/main/java/com/lunchchat/domain/member/service/MemberQueryServiceImpl.java
Labels: 🥡 CHORE

#67 [FEAT] 키워드 등록 및 조회 API 구현
  src/main/java/com/lunchchat/domain/member/controller/MemberController.java
  src/main/java/com/lunchchat/domain/member/dto/MemberRequestDTO.java
  src/main/java/com/lunchchat/domain/member/entity/Member.java
  src/main/java/com/lunchchat/domain/member/service/MemberCommandService.java
  src/main/java/com/lunchchat/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/lunchchat/domain/member/service/MemberQueryService.java
  src/main/java/com/lunchchat/domain/member/service/MemberQueryServiceImpl.java
  src/main/java/com/lunchchat/domain/user_keywords/converter/UserKeywordsConverter.java
  src/main/java/com/lunchchat/domain/user_keywords/entity/UserKeyword.java
  src/main/java/com/lunchchat/domain/user_keywords/repository/UserKeywordsRepository.java
  src/main/java/com/lunchchat/global/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/com/lunchchat/global/apiPayLoad/code/status/SuccessStatus.java
  src/main/resources/db/migration/V3__Update_user_keyword_table.sql
Labels: ✨ FEAT

#87 [REFACTOR] 채팅방 조회 api 개선
  src/main/java/com/lunchchat/domain/chat/controller/ChatRoomController.java
  src/main/java/com/lunchchat/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/lunchchat/domain/chat/service/ChatMessageService.java
  src/main/java/com/lunchchat/domain/chat/service/ChatRoomService.java
  src/main/java/com/lunchchat/global/apiPayLoad/CursorPaginatedResponse.java
Labels: 🔨 Refactor

#91 [FIX] FCM 푸시 알림 큐 처리 실패 해결
  src/main/java/com/lunchchat/LaunchatApplication.java
  src/main/java/com/lunchchat/domain/notification/service/NotificationQueueService.java
Labels: 🐞 BugFix, 🔨 Refactor

#89 [FEAT] 프로필 이미지 업로드 API 구현
  build.gradle
  docker-compose.yml
  src/main/java/com/lunchchat/LaunchatApplication.java
  src/main/java/com/lunchchat/domain/member/controller/AwsController.java
  src/main/java/com/lunchchat/domain/member/controller/MemberController.java
  src/main/java/com/lunchchat/domain/member/converter/MemberConverter.java
  src/main/java/com/lunchchat/domain/member/dto/MemberRequestDTO.java
  src/main/java/com/lunchchat/domain/member/dto/MemberResponseDTO.java
  src/main/java/com/lunchchat/domain/member/entity/Member.java
  src/main/java/com/lunchchat/domain/member/service/MemberCommandService.java
  src/main/java/com/lunchchat/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/lunchchat/domain/member/service/ProfileImageService.java
  src/main/java/com/lunchchat/domain/member/util/S3PresignedUrlUtil.java
  src/main/java/com/lunchchat/domain/notification/dto/response/NotificationResponseDTO.java
  src/main/java/com/lunchchat/global/apiPayLoad/code/status/SuccessStatus.java
  src/main/java/com/lunchchat/global/config/AwsS3Config.java
  src/main/java/com/lunchchat/global/config/AwsS3Properties.java
  src/main/resources/application.yml
Labels: ✨ FEAT

#92 [FEAT] 매칭 수락 API를 상대방 ID 기반으로 수정
  src/main/java/com/lunchchat/domain/match/controller/MatchRestController.java
  src/main/java/com/lunchchat/domain/match/repository/MatchRepository.java
  src/main/java/com/lunchchat/domain/match/service/MatchCommandService.java
  src/main/java/com/lunchchat/domain/match/service/MatchCommandServiceImpl.java
  src/main/java/com/lunchchat/global/apiPayLoad/code/status/SuccessStatus.java
Labels: ✨ FEAT

#96 [REFACTOR] 채팅방 반환 형식 수정
  src/main/java/com/lunchchat/domain/chat/dto/response/CreateChatRoomRes.java
  src/main/java/com/lunchchat/domain/chat/service/ChatRoomService.java
Labels: 🔨 Refactor

#104 [REFACTOR] InterestType enum에 GPA_MANAGEMENT 추가 및 ETC 제거
  src/main/java/com/lunchchat/domain/member/entity/enums/InterestType.java
  src/main/resources/db/migration/V4__Update_interest_data.sql
Labels: 🔨 Refactor

#107 [FEAT] 모니터링 재구축 및 디코 웹훅 추가
  .github/workflows/deploy.yml
  monitoring/alertmanager/alertmanager.yml.template
  monitoring/docker-compose.yml
  monitoring/grafana/dashboards/spring-boot-monitoring.json
  monitoring/grafana/dashboards/system-monitoring.json
  monitoring/prometheus/prometheus.yml.template
  monitoring/prometheus/rules/alerts.yml
Labels: ✨ FEAT

#109 [REMOVE] 필요없는 엔티티 삭제
  src/main/java/com/lunchchat/domain/project_info/entity/ProjectInfo.java
  src/main/resources/db/migration/V5__Drop_project_info_table.sql
Labels: 🥡 CHORE

#110 [BUGFIX] mongodb 문제 처리
  src/main/java/com/lunchchat/domain/chat/service/ChatRoomService.java
Labels: 🐞 BugFix

#111 [REFACTOR] 홈화면 매칭완료프로필 제외
  src/main/java/com/lunchchat/domain/match/repository/MatchRepository.java
  src/main/java/com/lunchchat/domain/member/service/MemberQueryServiceImpl.java
Labels: 🔨 Refactor

#117 [REFACTOR] 응답 형식 수정
  src/main/java/com/lunchchat/domain/chat/dto/response/ChatRoomCardRes.java
  src/main/java/com/lunchchat/domain/chat/service/ChatRoomService.java
Labels: 🔨 Refactor

#118 [BUGFIX] 채팅방 조회 시 내 정보 반환 문제
  src/main/java/com/lunchchat/domain/chat/controller/ChatRoomController.java
  src/main/java/com/lunchchat/domain/chat/service/ChatRoomService.java
Labels: 🐞 BugFix

#115 [BUGFIX] 매칭 횟수 반환 수정
  src/main/java/com/lunchchat/domain/member/service/MemberQueryServiceImpl.java
Labels: 🐞 BugFix

#119 [BUGFIX] 채팅방 조회시 lastMessageSendAt 갱신되는 문제 수정
  src/main/java/com/lunchchat/domain/chat/entity/ChatRoom.java
Labels: 🐞 BugFix

#122 [FEAT] Redis Stream 도입
  src/main/java/com/lunchchat/domain/chat/dto/response/ChatMessageRes.java
  src/main/java/com/lunchchat/domain/chat/redis/RedisPublisher.java
  src/main/java/com/lunchchat/domain/chat/redis/RedisStreamConsumer.java
  src/main/java/com/lunchchat/domain/chat/redis/RedisStreamProducer.java
  src/main/java/com/lunchchat/domain/chat/redis/RedisSubscriber.java
  src/main/java/com/lunchchat/domain/chat/service/ChatMessageService.java
  src/main/java/com/lunchchat/global/config/RedisConfig.java
Labels: 🐞 BugFix

#123 [REFACTOR] pub/sub 롤백
  src/main/java/com/lunchchat/domain/chat/dto/response/ChatMessageRes.java
  src/main/java/com/lunchchat/domain/chat/redis/RedisPublisher.java
  src/main/java/com/lunchchat/domain/chat/redis/RedisStreamConsumer.java
  src/main/java/com/lunchchat/domain/chat/redis/RedisStreamProducer.java
  src/main/java/com/lunchchat/domain/chat/redis/RedisSubscriber.java
  src/main/java/com/lunchchat/domain/chat/service/ChatMessageService.java
  src/main/java/com/lunchchat/global/config/RedisConfig.java
Labels: 🐞 BugFix

#125 [DEPLOY] JVM 최적화
  ansible/templates/docker-compose.app.yml.j2
Labels: 🌏 Deploy

#127 [FIX] JVM 오류 해결
  ansible/templates/docker-compose.app.yml.j2
Labels: 🐞 BugFix

#129 [REFACTOR] Redis Stream 적용
  src/main/java/com/lunchchat/domain/chat/config/StompHandler.java
  src/main/java/com/lunchchat/domain/chat/dto/response/ChatMessageRes.java
  src/main/java/com/lunchchat/domain/chat/redis/DynamicStreamConsumerManager.java
  src/main/java/com/lunchchat/domain/chat/redis/OptimizedRedisStreamProducer.java
  src/main/java/com/lunchchat/domain/chat/redis/RedisPublisher.java
  src/main/java/com/lunchchat/domain/chat/redis/RedisSubscriber.java
  src/main/java/com/lunchchat/domain/chat/service/ChatMessageService.java
  src/main/java/com/lunchchat/domain/chat/service/WebSocketSessionManager.java
  src/main/java/com/lunchchat/global/config/RedisConfig.java
Labels: 🔨 Refactor
