Repository LUNCH-CHAT/BACKEND, pull requests merged in 2025-07, with the labels that each got.

#7 [SETTING] Docker 세팅
  Dockerfile
  build.gradle
  docker-compose.yml
Labels: ⚙️ Setting

#9 [SETTING] 초기 엔티티 세팅
  src/main/java/com/lunchchat/domain/chat_message/entity/ChatMessage.java
  src/main/java/com/lunchchat/domain/chat_participant/entity/ChatParticipant.java
  src/main/java/com/lunchchat/domain/chat_participant/entity/ChatParticipantId.java
  src/main/java/com/lunchchat/domain/chat_room/entity/ChatRoom.java
  src/main/java/com/lunchchat/domain/college/entity/College.java
  src/main/java/com/lunchchat/domain/department/entity/Department.java
  src/main/java/com/lunchchat/domain/faq/entity/Faq.java
  src/main/java/com/lunchchat/domain/interests/entity/InterestName.java
  src/main/java/com/lunchchat/domain/interests/entity/Interests.java
  src/main/java/com/lunchchat/domain/match/entity/Match.java
  src/main/java/com/lunchchat/domain/match/entity/MatchStatus.java
  src/main/java/com/lunchchat/domain/notifications/entity/Notification.java
  src/main/java/com/lunchchat/domain/project_info/entity/ProjectInfo.java
  src/main/java/com/lunchchat/domain/time_table/entity/DayOfWeek.java
  src/main/java/com/lunchchat/domain/time_table/entity/TimeTable.java
  src/main/java/com/lunchchat/domain/user_interests/entity/UserInterests.java
  src/main/java/com/lunchchat/domain/user_interests/entity/UserInterestsId.java
  src/main/java/com/lunchchat/domain/user_keywords/entity/KeywordType.java
  src/main/java/com/lunchchat/domain/user_keywords/entity/UserKeyword.java
  src/main/java/com/lunchchat/domain/users/entity/User.java
Labels: ⚙️ Setting

#13 [CHORE] local.yml, gitignore 수정
  .gitignore
  src/main/resources/application-local.yml
Labels: 🥡 CHORE

#22 [FEAT] 매칭 조회, 요청, 수락, 거절 API 구현
  src/main/java/com/lunchchat/domain/interests/entity/Interests.java
  src/main/java/com/lunchchat/domain/match/controller/MatchRestController.java
  src/main/java/com/lunchchat/domain/match/converter/MatchConverter.java
  src/main/java/com/lunchchat/domain/match/dto/MatchRequestDto.java
  src/main/java/com/lunchchat/domain/match/dto/MatchResponseDto.java
  src/main/java/com/lunchchat/domain/match/dto/enums/MatchStatusType.java
  src/main/java/com/lunchchat/domain/match/entity/MatchStatus.java
  src/main/java/com/lunchchat/domain/match/entity/Matches.java
  src/main/java/com/lunchchat/domain/match/repository/MatchRepository.java
  src/main/java/com/lunchchat/domain/match/service/MatchCommandService.java
  src/main/java/com/lunchchat/domain/match/service/MatchCommandServiceImpl.java
  src/main/java/com/lunchchat/domain/match/service/MatchQueryService.java
  src/main/java/com/lunchchat/domain/match/service/MatchQueryServiceImpl.java
  src/main/java/com/lunchchat/domain/member/entity/Member.java
  src/main/java/com/lunchchat/domain/member/repository/MemberRepository.java
  src/main/java/com/lunchchat/domain/user_interests/entity/UserInterestsId.java
  src/main/java/com/lunchchat/domain/user_keywords/entity/UserKeyword.java
  src/main/java/com/lunchchat/domain/user_statistics/entity/UserStatistics.java
  src/main/java/com/lunchchat/domain/user_statistics/repository/UserStatisticsRepository.java
  src/main/java/com/lunchchat/domain/user_statistics/service/UserStatisticsCommandService.java
  src/main/java/com/lunchchat/domain/user_statistics/service/UserStatisticsCommandServiceImpl.java
  src/main/java/com/lunchchat/global/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/com/lunchchat/global/apiPayLoad/exception/handler/MatchException.java
Labels: ✨ FEAT

#26 [FEAT] 단과대 목록 조회, 특정 단과대의 학과 목록 조회 (#20)(#21)
  src/main/java/com/lunchchat/domain/college/controller/CollegeController.java
  src/main/java/com/lunchchat/domain/college/dto/CollegeResponseDTO.java
  src/main/java/com/lunchchat/domain/college/repository/CollegeRepository.java
  src/main/java/com/lunchchat/domain/college/service/CollegeQueryService.java
  src/main/java/com/lunchchat/domain/college/service/CollegeQueryServiceImpl.java
  src/main/java/com/lunchchat/domain/department/controller/DepartmentController.java
  src/main/java/com/lunchchat/domain/department/dto/DepartmentResponseDTO.java
  src/main/java/com/lunchchat/domain/department/repository/DepartmentRepository.java
  src/main/java/com/lunchchat/domain/department/service/DepartmentQueryService.java
  src/main/java/com/lunchchat/domain/department/service/DepartmentQueryServiceImpl.java
Labels: ✨ FEAT

#29 [FEAT] 마이페이지 정보 조회 API 구현
  src/main/java/com/lunchchat/domain/member/controller/MemberController.java
  src/main/java/com/lunchchat/domain/member/converter/MemberConverter.java
  src/main/java/com/lunchchat/domain/member/converter/MemberRecommendationConverter.java
  src/main/java/com/lunchchat/domain/member/dto/MemberDetailResponseDTO.java
  src/main/java/com/lunchchat/domain/member/dto/MemberRecommendationResponseDTO.java
  src/main/java/com/lunchchat/domain/member/dto/MemberResponseDTO.java
  src/main/java/com/lunchchat/domain/member/service/MemberQueryService.java
  src/main/java/com/lunchchat/domain/member/service/MemberQueryServiceImpl.java
  src/main/java/com/lunchchat/domain/user_interests/repository/UserInterestsRepository.java
  src/main/java/com/lunchchat/domain/user_keywords/repository/UserKeywordsRepository.java
  src/main/java/com/lunchchat/domain/user_statistics/entity/UserStatistics.java
  src/main/java/com/lunchchat/domain/user_statistics/repository/UserStatisticsRepository.java
  src/main/java/com/lunchchat/domain/user_statistics/service/UserStatisticsCommandServiceImpl.java
  src/main/java/com/lunchchat/global/apiPayLoad/code/status/ErrorStatus.java
Labels: ✨ FEAT

#30 [FEAT] 구글 로그인 구현
  build.gradle
  src/main/java/com/lunchchat/.DS_Store
  src/main/java/com/lunchchat/domain/.DS_Store
  src/main/java/com/lunchchat/domain/match/controller/MatchRestController.java
  src/main/java/com/lunchchat/domain/member/.DS_Store
  src/main/java/com/lunchchat/domain/member/entity/Member.java
  src/main/java/com/lunchchat/domain/member/repository/MemberRepository.java
  src/main/java/com/lunchchat/domain/university/.DS_Store
  src/main/java/com/lunchchat/global/.DS_Store
  src/main/java/com/lunchchat/global/apiPayLoad/.DS_Store
  src/main/java/com/lunchchat/global/apiPayLoad/ApiResponse.java
  src/main/java/com/lunchchat/global/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/com/lunchchat/global/apiPayLoad/code/status/SuccessStatus.java
  src/main/java/com/lunchchat/global/apiPayLoad/exception/AuthException.java
  src/main/java/com/lunchchat/global/apiPayLoad/exception/GeneralException.java
  src/main/java/com/lunchchat/global/apiPayLoad/exception/InvalidTokenException.java
  src/main/java/com/lunchchat/global/apiPayLoad/exception/handler/AuthHandler.java
  src/main/java/com/lunchchat/global/config/SwaggerConfig.java
  src/main/java/com/lunchchat/global/config/WebConfig.java
  src/main/java/com/lunchchat/global/config/security/AuthenticationConfig.java
  src/main/java/com/lunchchat/global/config/security/CorsConfig.java
  src/main/java/com/lunchchat/global/config/security/JwtConfig.java
  src/main/java/com/lunchchat/global/config/security/JwtFilterConfig.java
  src/main/java/com/lunchchat/global/config/security/SecurityConfig.java
  src/main/java/com/lunchchat/global/security/.DS_Store
  src/main/java/com/lunchchat/global/security/auth/.DS_Store
  src/main/java/com/lunchchat/global/security/auth/controller/OAuthController.java
  src/main/java/com/lunchchat/global/security/auth/dto/CustomUserDetails.java
  src/main/java/com/lunchchat/global/security/auth/dto/GoogleUserDTO.java
  src/main/java/com/lunchchat/global/security/auth/infra/GoogleOAuthProperties.java
  src/main/java/com/lunchchat/global/security/auth/infra/GoogleUtil.java
  src/main/java/com/lunchchat/global/security/auth/service/CustomUserDetailsService.java
  src/main/java/com/lunchchat/global/security/auth/service/GoogleAuthService.java
  src/main/java/com/lunchchat/global/security/jwt/JwtFilter.java
  src/main/java/com/lunchchat/global/security/jwt/JwtTokenProvider.java
  src/main/java/com/lunchchat/global/security/jwt/JwtUtil.java
  src/main/resources/application-local.yml
Labels: ✨ FEAT

#28 [FEAT] FCM 푸시알림 구현
  build.gradle
  src/main/java/com/lunchchat/domain/match/service/MatchCommandServiceImpl.java
  src/main/java/com/lunchchat/domain/match/service/MatchNotificationService.java
  src/main/java/com/lunchchat/domain/match/service/MatchNotificationServiceImpl.java
  src/main/java/com/lunchchat/domain/member/controller/MemberController.java
  src/main/java/com/lunchchat/domain/member/entity/Member.java
  src/main/java/com/lunchchat/domain/member/service/MemberCommandService.java
  src/main/java/com/lunchchat/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/lunchchat/domain/notification/dto/FcmSendDto.java
  src/main/java/com/lunchchat/domain/notification/dto/FcmUpdateRequestDto.java
  src/main/java/com/lunchchat/domain/notification/entity/Notification.java
  src/main/java/com/lunchchat/domain/notification/repository/NotificationRepository.java
  src/main/java/com/lunchchat/domain/notification/service/FcmService.java
  src/main/java/com/lunchchat/global/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/com/lunchchat/global/apiPayLoad/code/status/SuccessStatus.java
  src/main/java/com/lunchchat/global/config/FcmConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: ✨ FEAT

#43 [DEPLOY] 브랜치별 환경변수 분리
  .github/workflows/deploy.yml
Labels: 🌏 Deploy

#47 [SETTING] CodeRabbit 도입
  .coderabbit.yml
Labels: ⚙️ Setting

#50 [BUGFIX] FE 로컬에 맞춰 RURI 값 수정
  src/main/java/com/lunchchat/global/security/auth/controller/OAuthController.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: 🐞 BugFix

#51 [FEAT] 알림 조회 및 전송 구현
  src/main/java/com/lunchchat/domain/match/controller/MatchRestController.java
  src/main/java/com/lunchchat/domain/match/dto/MatchRequestDto.java
  src/main/java/com/lunchchat/domain/match/service/MatchNotificationServiceImpl.java
  src/main/java/com/lunchchat/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/lunchchat/domain/notification/controller/NotificationController.java
  src/main/java/com/lunchchat/domain/notification/dto/response/NotificationResponseDTO.java
  src/main/java/com/lunchchat/domain/notification/entity/Notification.java
  src/main/java/com/lunchchat/domain/notification/entity/enums/NotificationType.java
  src/main/java/com/lunchchat/domain/notification/repository/NotificationRepository.java
  src/main/java/com/lunchchat/domain/notification/service/FcmService.java
  src/main/java/com/lunchchat/domain/notification/service/FcmTokenCacheService.java
  src/main/java/com/lunchchat/domain/notification/service/NotificationCommandService.java
  src/main/java/com/lunchchat/domain/notification/service/NotificationCommandServiceImpl.java
  src/main/java/com/lunchchat/domain/notification/service/NotificationDuplicationService.java
  src/main/java/com/lunchchat/domain/notification/service/NotificationQueryService.java
  src/main/java/com/lunchchat/domain/notification/service/NotificationQueryServiceImpl.java
  src/main/java/com/lunchchat/domain/notification/service/NotificationQueueService.java
  src/main/java/com/lunchchat/global/config/AsyncConfig.java
Labels: ✨ FEAT

#57 [FEAT] 관심사 태그 관련 API 구현
  src/main/java/com/lunchchat/domain/member/controller/MemberController.java
  src/main/java/com/lunchchat/domain/member/dto/MemberRequestDTO.java
  src/main/java/com/lunchchat/domain/member/service/MemberCommandService.java
  src/main/java/com/lunchchat/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/lunchchat/domain/user_interests/controller/UserInterestController.java
  src/main/java/com/lunchchat/domain/user_interests/converter/UserInterestConverter.java
  src/main/java/com/lunchchat/domain/user_interests/dto/UserInterestResponseDTO.java
  src/main/java/com/lunchchat/domain/user_interests/service/UserInterestQueryService.java
  src/main/java/com/lunchchat/domain/user_interests/service/UserInterestQueryServiceImpl.java
  src/main/java/com/lunchchat/global/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/com/lunchchat/global/apiPayLoad/code/status/SuccessStatus.java
Labels: ✨ FEAT

#62 [REFACTOR] 알림 API 수정
  src/main/java/com/lunchchat/domain/member/controller/MemberController.java
  src/main/java/com/lunchchat/domain/member/service/MemberCommandService.java
  src/main/java/com/lunchchat/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/lunchchat/domain/notification/controller/NotificationController.java
  src/main/java/com/lunchchat/domain/notification/dto/response/NotificationCursorResponseDTO.java
  src/main/java/com/lunchchat/domain/notification/dto/response/NotificationResponseDTO.java
  src/main/java/com/lunchchat/domain/notification/repository/NotificationRepository.java
  src/main/java/com/lunchchat/domain/notification/service/NotificationQueryService.java
  src/main/java/com/lunchchat/domain/notification/service/NotificationQueryServiceImpl.java
Labels: 🔨 Refactor
